version: "3.9"

services:
  jaknaweb:
    image: custom-nginx:tul.41
    build:
        context: .
    container_name: jaknaweb
    restart: "always"
    volumes:
      - ./web:/static:ro
    labels:
      - "traefik.http.routers.jaknaweb_https.rule=Host(`jaknaweb.dcreative.cz`)"
      - "traefik.http.routers.jaknaweb_https.entrypoints=websecure"
      - "traefik.http.routers.jaknaweb_https.tls=true"
      - "traefik.http.routers.jaknaweb_https.tls.certResolver=lets-encrypt"

networks:
  default:
    name: web